### ISSUE TITLE
Listener leak; callbacks not invoked for commands without response bodies

### ISSUE THREAD

**Issue by zbjornson** [hden/node-serf#10]
For commands that don't have responses (e.g. 'tags', 'event', 'auth', 'handshake', ...) it appears that the callback will never be invoked. Consequently the `once` listeners will never be released == leak.

--

I'm evaluating this library as an alternative to the 'serf-rpc' library (which has a few critical bugs and unclear maintenance status -- looks like it was actually a port of this library). Are you actively accepting pull requests? In addition to the above, there are a few other changes I'd propose (including traditional error-first callbacks that are always invoked, supporting the rest of the methods, and maybe porting the coffeescript to JS if you're open to it).

**Comment by hden** [comment]
Pull requests are welcomed. 😄 

If we can agree on one coding style e.g. ([feross/standard](https://github.com/feross/standard)), proving to JS sounds good to be.

**Comment by zbjornson** [comment]
Awesome! What do you think of feross/standard + semicolons? :)

**Comment by hden** [comment]
Personally I'm not a big fan of semicolons, but I can certainly live with that. :)

**Comment by zbjornson** [comment]
Hmm, I'll give no-semis a try :)
