### ISSUE TITLE
v1.0.0 Proposal

### ISSUE THREAD

**Issue by zbjornson** [hden/node-serf#12]
For discussion...

Breaking changes:
* Use node.js-style error-first callbacks (PR #14, e3ed332)

Bug fixes:
* Invoke callbacks for methods without response bodies; fix listener leak. (bug #10, PR #13, c51fab5)
* Don't invoke `connect` callback until after handshake (PR #15, cca18c5)

New features:
* Implement all Serf methods (PR #13, c51fab5)
* Add a default connection syntax: `Serf.connect(function () {...})` -> connects to 127.0.0.1:7373 (PR #18)

Source changes:
* Upgrade msgpack dependency (bug #15, PR #19)

**Comment by hden** [comment]
+ CHANGELOG

**Comment by zbjornson** [comment]
Now that everything is merged, I'm happy with this as 1.0.0. I've been using this library all day and haven't encountered any problems.

**Comment by hden** [comment]
Published as `node-serf@1.0.0`

**Comment by zbjornson** [comment]
Awesome, thanks for supporting this!
