### ISSUE TITLE
Update msgpack library from msgpack-js-v5-ng to msgpack5

### ISSUE THREAD

**Issue by hden** [hden/node-serf#15]
Since [msgpack-js-v5-ng](https://github.com/hden/msgpack-js) is not being actively maintained, we probably want to switch to something reliable e.g. [msgpack5](https://github.com/mcollina/msgpack5).

**Comment by zbjornson** [comment]
I was also looking at https://github.com/kawanet/msgpack-lite, which has the fastest benchmarks (see the readme and [some 3rd party benchmarks](https://github.com/endel/msgpack-benchmark)), and has a streaming interface so node-serf wouldn't have to do any stream handling.
