### ISSUE TITLE
Improve error message in unit tests

### ISSUE THREAD

**Issue by hden** [hden/node-serf#16]
chai.assert provides human friendly assertion message through standard assert interface. However, it can be much more descriptive if we switch to [power-assert](https://github.com/power-assert-js/power-assert).

Since we are using the standard assertion interface, the switching cost should be very low. No API is the best API.

**Comment by zbjornson** [comment]
Will do this tomorrow, then aside from the changelog I think 1.0.0 is basically ready!

**Comment by hden** [comment]
Cool!
