### ISSUE TITLE
Release 1.0.0 depends on git version of msgpack-lite

### ISSUE THREAD

**Issue by martiell** [hden/node-serf#28]
Hi,

The [package.json](https://github.com/hden/node-serf/blob/v1.0.0/package.json) for v1.0.0 specifies a dependency on a git version of msgpack-lite (somewhere around/after 0.1.25). msgpack-lite 0.1.26 was released about a month after node-serf v1.0.0.

It would be great to have a release of node-serf that depends on a release version (instead of a git version). This would help in build pipelines that using a caching npm proxy.

Please consider making a new release that bumps version to, say, `~0.1.26`.

Thanks. :)

**Comment by hden** [comment]
Released as `v1.1.0`
